### PR TITLE
Fetch cartographer to release-1.0 tag

### PR DESCRIPTION
**Pull request by routiful**
I fetched cartographer code to release-1.0 tag in googlecartographer/cartographer repo.
I have been tested this turtlebot3 and gazebo.

If you want to test this, please following below link
http://emanual.robotis.com/docs/en/platform/turtlebot3/ros2/#ros2

### CODE REVIEW

**Comment by clalancette** [comment]
@routiful It is great to get this up-to-date, so thanks for the PR.  I'm actually wondering if it might make more sense to just force push this repository up to the latest cartographer code, then add the changes we need on top of that as a new rebase.  That will reduce the history (since it is a bit confusing now), and get rid of the merge.

Separately, we should also look at pushing these changes into upstream cartographer, and seeing what their thoughts about it are, but that can wait until later.

What do you think?

**Comment by routiful** [comment]
@clalancette 
I agreed your opinion. In my thought, after this branch are going to be rebased from cartographer-1.0.0 tag, I would be modified the cmakelist to build using colcon. It might be make more sense.

Since I didn't modified this code except cmakelist to build in colcon, I don't think this code should be a reviewed. 
But cartographer_ros(https://github.com/ros2/cartographer_ros/pull/25) might be reviewed to cartographer developer. But I was wondering when they start, either.
I will write a comment to review PR at cartographer_ros to  RFCs(https://github.com/googlecartographer/rfcs).

I have a plan to other nodes including cartographer_ros. 
If I get more progress, I will let you know about it :)

**Comment by dirk-thomas** [comment]
> Since I didn't modified this code except cmakelist to build in colcon ...

Can you please describe what you mean with this? Or even better provide a link to the actual diff between the CMake code upstream and in this fork?

**Comment by routiful** [comment]
@dirk-thomas 

I've deleted `google test` line in CMakelists when I started fetch this repo.
https://github.com/ros2/cartographer/pull/7/commits/bdf4a5766d49488434bd9a5bf354ba3ca2efd5f0
I assume that it was caused by dependency problem. 

For now,  I test again with activated test line I said, colcon build was successfully finished including one warning. 

```
➜  ros2_overlay_ws colcon build --packages-select cartographer 
Starting >>> cartographer
[Processing: cartographer]                             
[Processing: cartographer]                                     
[Processing: cartographer]                                       
[Processing: cartographer]                                       
--- stderr: cartographer                                            
In file included from /usr/src/googletest/googlemock/include/gmock/gmock-spec-builders.h:75:0,
                 from /usr/src/googletest/googlemock/include/gmock/gmock-generated-function-mockers.h:43,
                 from /usr/src/googletest/googlemock/include/gmock/gmock.h:61,
                 from /home/ost/ros2_overlay_ws/src/cartographer/cartographer/io/serialization_format_migration_test.cc:27:
/usr/src/googletest/googlemock/include/gmock/gmock-matchers.h: In instantiation of ‘bool testing::internal::AnyEq::operator()(const A&, const B&) const [with A = unsigned int; B = int]’:
/usr/src/googletest/googlemock/include/gmock/gmock-matchers.h:908:18:   required from ‘bool testing::internal::ComparisonBase<D, Rhs, Op>::Impl<Lhs>::MatchAndExplain(Lhs, testing::MatchResultListener*) const [with Lhs = const unsigned int&; D = testing::internal::EqMatcher<int>; Rhs = int; Op = testing::internal::AnyEq]’
/home/ost/ros2_overlay_ws/src/cartographer/cartographer/io/serialization_format_migration_test.cc:120:1:   required from here
/usr/src/googletest/googlemock/include/gmock/gmock-matchers.h:204:60: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   bool operator()(const A& a, const B& b) const { return a == b; }
                                                          ~~^~~~
---
Finished <<< cartographer [2min 24s]

Summary: 1 package finished [2min 25s]
  1 package had stderr output: cartographer
```

**Comment by dirk-thomas** [comment]
> colcon build was successfully finished including one warning.

I would assume that the same warning is also present when building the upstream package? If yes, I would suggest to propose a PR upstream to address the compiler warning and once that patch got accepted we can use upstream unmodified.

**Comment by routiful** [comment]
@dirk-thomas 
I've tested upstream packages(release-1.0) has same warning.
I agree your suggestion to upstream this package.

**Comment by clalancette** [comment]
I'm sorry for the long delay here.  After looking at the difference between this PR as it is and upstream, it looks like the only difference is a single `#include <array>` in cartographer/mapping/pose_graph_interface.h, and the changing of the maintainers.  Therefore, what I'm going to do is the following:

1.  Update the ros2 branch here by fetching from upstream cartographer 1.0.0 and force-pushing to the `ros2` branch here.
1.  Add in a single commit on top changing the maintainer to me and @mjcarroll , with Pyo as an author.
1.  Close this PR.
1.  Release this package into crystal.

**Comment by clalancette** [comment]
Done now, so closing this PR.

**Comment by routiful** [comment]
@clalancette 

Thanks you so much :)

**Pull request closed without merging**
